name: Delete branch on issue close
on:
  issues:
    types:
      - closed

jobs:
  delete-branch:
    name: Delete associated branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Issue Parser
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/issue_form.yml

      - name: Find and delete branch
        run: |
          # Get issue information
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          BRANCH_NAME="${{ steps.issue-parser.outputs.issueparser_branchName }}"
          PARENT_KEY="${{ steps.issue-parser.outputs.issueparser_parentKey }}"
          
          echo "Looking for branches with:"
          echo "- Parent Key: $PARENT_KEY"
          echo "- Branch Name: $BRANCH_NAME"
          echo "- Issue Number: $ISSUE_NUMBER"
          
          # Find exact match: PARENT_KEY-BRANCH_NAME or PARENT_KEY-gh{ISSUE_NUMBER}-BRANCH_NAME
          EXACT_BRANCH_1="${PARENT_KEY}-${BRANCH_NAME}"
          EXACT_BRANCH_2="${PARENT_KEY}-gh${ISSUE_NUMBER}-${BRANCH_NAME}"
          
          BRANCHES_DELETED=0
          
          # Check for exact branch name (PARENT_KEY-BRANCH_NAME)
          if git show-ref --verify --quiet refs/remotes/origin/$EXACT_BRANCH_1; then
            echo "Found exact match branch: $EXACT_BRANCH_1"
            git push origin --delete "$EXACT_BRANCH_1" && echo "Successfully deleted: $EXACT_BRANCH_1" || echo "Failed to delete: $EXACT_BRANCH_1"
            BRANCHES_DELETED=1
          fi
          
          # Check for GitHub issue tagged branch (PARENT_KEY-gh{ISSUE_NUMBER}-BRANCH_NAME)
          if git show-ref --verify --quiet refs/remotes/origin/$EXACT_BRANCH_2; then
            echo "Found GitHub tagged branch: $EXACT_BRANCH_2"
            git push origin --delete "$EXACT_BRANCH_2" && echo "Successfully deleted: $EXACT_BRANCH_2" || echo "Failed to delete: $EXACT_BRANCH_2"
            BRANCHES_DELETED=1
          fi
          
          # If no exact matches found, report and continue
          if [ $BRANCHES_DELETED -eq 0 ]; then
            echo "::warning::No matching branch found for Parent Key: $PARENT_KEY, Branch Name: $BRANCH_NAME"
            echo "Expected branches: $EXACT_BRANCH_1 or $EXACT_BRANCH_2"
            echo "This issue will be closed without branch deletion."
          else
            echo "Branch deletion completed successfully."
          fi

      - name: Log completion
        run: |
          echo "Branch deletion workflow completed for issue #${{ github.event.issue.number }}"
