name: Close Jira Issue and Delete Branch
on:
  issues:
    types:
      - closed

jobs:
  close-issue:
    name: Close Jira Issue and Delete Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Issue Parser
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/issue_form.yml

      - name: Find and delete branch by branch name
        run: |
          BRANCH_NAME="${{ steps.issue-parser.outputs.issueparser_branchName }}"
          
          echo "Looking for branches containing: $BRANCH_NAME"
          
          # Find branches that contain the branch name
          MATCHING_BRANCHES=$(git branch -r | grep -E "origin/.*${BRANCH_NAME}" | sed 's/origin\///' | sed 's/^ *//' | xargs)
          
          if [ -n "$MATCHING_BRANCHES" ]; then
            for BRANCH in $MATCHING_BRANCHES; do
              echo "Found branch: $BRANCH"
              
              # Extract Jira ticket number from branch name (앞부분)
              JIRA_TICKET=$(echo "$BRANCH" | grep -oE '^[A-Z]+-[0-9]+' | head -1)
              
              if [ -n "$JIRA_TICKET" ]; then
                echo "Extracted Jira ticket: $JIRA_TICKET from branch: $BRANCH"
                echo "JIRA_TICKET=$JIRA_TICKET" >> $GITHUB_ENV
              fi
              
              echo "Deleting branch: $BRANCH"
              git push origin --delete "$BRANCH" && echo "Successfully deleted: $BRANCH" || echo "Failed to delete: $BRANCH"
            done
          else
            echo "No matching branches found for branch name: $BRANCH_NAME"
          fi

      - name: Login to Jira
        if: env.JIRA_TICKET != ''
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Transition Jira Issue to Done
        if: env.JIRA_TICKET != ''
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ env.JIRA_TICKET }}
          transition: "완료"

      - name: Add comment on GitHub issue
        if: env.JIRA_TICKET != ''
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: 'Jira Issue Closed: [${{ env.JIRA_TICKET }}](${{ secrets.JIRA_BASE_URL }}/browse/${{ env.JIRA_TICKET }})'