name: Delete branch on issue close
on:
  issues:
    types:
      - closed

jobs:
  delete-branch:
    name: Delete associated branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Issue Parser
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/issue_form.yml

      - name: Find and delete branch
        run: |
          # Get issue information
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          BRANCH_NAME="${{ steps.issue-parser.outputs.issueparser_branchName }}"
          
          echo "Looking for branches with:"
          echo "- Issue Number: $ISSUE_NUMBER"
          echo "- Branch Name: $BRANCH_NAME"
          
          # Find branches that match the pattern: {JIRA_TICKET}-{SANITIZED_BRANCH_NAME}
          # The branch name format from creation: {ISSUE_NUMBER}-{SANITIZED_BRANCH_NAME}
          SANITIZED_BRANCH=$(echo "${BRANCH_NAME}" | sed 's/ /-/g')
          TARGET_BRANCH_PATTERN="${ISSUE_NUMBER}-${SANITIZED_BRANCH}"
          
          echo "Looking for branch pattern: $TARGET_BRANCH_PATTERN"
          
          BRANCHES_DELETED=0
          
          # Find branches that match the exact pattern
          MATCHING_BRANCHES=$(git branch -r | grep -E "origin/${TARGET_BRANCH_PATTERN}$" | sed 's/origin\///' | sed 's/^ *//' | xargs)
          
          if [ -n "$MATCHING_BRANCHES" ]; then
            for BRANCH in $MATCHING_BRANCHES; do
              echo "Found matching branch: $BRANCH"
              git push origin --delete "$BRANCH" && echo "Successfully deleted: $BRANCH" || echo "Failed to delete: $BRANCH"
              BRANCHES_DELETED=1
            done
          fi
          
          # If no exact matches found, report and continue
          if [ $BRANCHES_DELETED -eq 0 ]; then
            echo "::warning::No matching branch found for pattern: $TARGET_BRANCH_PATTERN"
            echo "This issue will be closed without branch deletion."
          else
            echo "Branch deletion completed successfully."
          fi

      - name: Log completion
        run: |
          echo "Branch deletion workflow completed for issue #${{ github.event.issue.number }}"
