name: Delete branch on issue close
on:
  issues:
    types:
      - closed

jobs:
  delete-branch:
    name: Delete associated branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Issue Parser
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/issue_form.yml

      - name: Find and delete branch
        run: |
          # Use GitHub issue number to find associated branches
          # Pattern: any branch containing the GitHub issue number and branch name
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          BRANCH_NAME="${{ steps.issue-parser.outputs.issueparser_branchName }}"
          
          # Find branches that contain both issue number and branch name
          # This handles cases where JIRA ticket number might vary
          MATCHING_BRANCHES=$(git branch -r | grep -E "origin/.*${ISSUE_NUMBER}.*${BRANCH_NAME}" | sed 's/origin\///' | sed 's/^ *//' | xargs)
          
          if [ -n "$MATCHING_BRANCHES" ]; then
            for BRANCH in $MATCHING_BRANCHES; do
              echo "Deleting branch: $BRANCH"
              git push origin --delete "$BRANCH" || echo "Failed to delete branch $BRANCH or branch already deleted"
            done
          else
            echo "No matching branches found for issue #${ISSUE_NUMBER} with branch name: ${BRANCH_NAME}"
            # Fallback: try to find any branch with the branch name
            FALLBACK_BRANCHES=$(git branch -r | grep -E "origin/.*${BRANCH_NAME}" | sed 's/origin\///' | sed 's/^ *//' | xargs)
            if [ -n "$FALLBACK_BRANCHES" ]; then
              echo "Found fallback branches: $FALLBACK_BRANCHES"
              for BRANCH in $FALLBACK_BRANCHES; do
                echo "Deleting fallback branch: $BRANCH"
                git push origin --delete "$BRANCH" || echo "Failed to delete branch $BRANCH or branch already deleted"
              done
            fi
          fi

      - name: Log completion
        run: |
          echo "Branch deletion workflow completed for issue #${{ github.event.issue.number }}"
